function joinQueue(p: player):
	if number of online players > 1:
		if {tagger} is not set:
			if {queue::*} does not contain {_p}:
				if {players::*} does not contain {_p}:
					if {CountdownToStart} is not set:
						add {_p} to {queue::*}
						send "&eYou have joined the queue!" to {_p}
						if size of {queue::*} >= 2:
							startGame()
						else:
							send formatted "<cmd:/queue>&eThere is a player in the queue! Join the queue or click me to play tag with them!" to all players
					else:
						# if chaning code below, also change in startGame() below other comment
						teleport {_p} to spawn of {TagWorld}
						clear {_p}'s inventory
				else:
					send "&cYou are already in the queue!" to {_p}
			else:
				send "&cYou are already in the queue!" to {_p}
		else:
			if {players::*} does not contain {_p}:
				send "&eYou joined the game!" to {_p}
				teleport {_p} to spawn of {TagWorld}
				add {_p} to {players::*}
				broadcast "&2&l%{_p}%&a has joined the tag game!" to {TagWorld}
				clear {_p}'s inventory
				wait 1 tick
				giveItems({_p})
				modifyTeam({_p}, "runner")
			else:
				send "&cYou are already in the game! If this is an error, do /spawn!" to {_p}
	else:
		send "&cYou are the only player online! Invite someone to play with you!" to {_p}